/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.scilab.forge.java-conventions")
}

dependencies {
    api(project(":jlatexmath-font-greek"))
    api(project(":jlatexmath-font-cyrillic"))
    testImplementation("junit:junit:4.12")
    testImplementation("org.openjdk.jmh:jmh-core:1.19")
    testImplementation("org.openjdk.jmh:jmh-generator-annprocess:1.19")
}

description = "jlatexmath"

// No Javadoc
tasks.javadoc {
    enabled = false
}
