/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.scilab.forge.java-conventions")
}

dependencies {
    api(project(":jlatexmath"))
    api("org.apache.xmlgraphics:fop:1.0")
    testImplementation("junit:junit:4.12")
}

description = "jlatexmath-fop"

// No Javadoc
tasks.javadoc {
    enabled = false
}
