/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "jlatexmath-parent"
// include(":jlatexmath-example-giws")
include(":jlatexmath-font-cyrillic")
include(":jlatexmath-font-greek")
include(":jlatexmath-ignore")
include(":jlatexmath-fop")
// include(":jlatexmath-example-export")
include(":jlatexmath")
