/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.scilab.forge.java-conventions")
}

dependencies {
    api(project(":jlatexmath"))
    api("org.apache.xmlgraphics:fop:1.0")
    api("org.apache.xmlgraphics:batik-codec:1.7")
    api("org.apache.xmlgraphics:xmlgraphics-commons:2.1")
    testImplementation("junit:junit:4.12")
}

description = "jlatexmath-example-export"

java {
    withJavadocJar()
}
