/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.scilab.forge.java-conventions")
}

dependencies {
    api(project(":jlatexmath"))
    testImplementation("junit:junit:4.12")
}

description = "jlatexmath-example-giws"

java {
    withJavadocJar()
}
